USE [master]
GO

CREATE DATABASE [Master_CarManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Master_CarManager', FILENAME = N'E:\Programs\SqlServer\MSSQL14.VITALI_DESKTOP\MSSQL\DATA\Master_CarManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [G1] 
( NAME = N'Global_CarManager', FILENAME = N'E:\Programs\SqlServer\MSSQL14.VITALI_DESKTOP\MSSQL\DATA\M1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Master_CarManager_log', FILENAME = N'E:\Programs\SqlServer\MSSQL14.VITALI_DESKTOP\MSSQL\DATA\Master_CarManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Master_CarManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Master_CarManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Master_CarManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Master_CarManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Master_CarManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Master_CarManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [Master_CarManager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Master_CarManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Master_CarManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Master_CarManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Master_CarManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Master_CarManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Master_CarManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Master_CarManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Master_CarManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Master_CarManager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Master_CarManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Master_CarManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Master_CarManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Master_CarManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Master_CarManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Master_CarManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Master_CarManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Master_CarManager] SET RECOVERY FULL 
GO

ALTER DATABASE [Master_CarManager] SET  MULTI_USER 
GO

ALTER DATABASE [Master_CarManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Master_CarManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Master_CarManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Master_CarManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Master_CarManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Master_CarManager] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Master_CarManager] SET  READ_WRITE 
GO


